const Data = [
  {
    id: 1,
    availableSizes: ["X", "L", "XL", "XXL"],
    currencyFormat: "$",
    currencyId: "USD",
    description: "1.21",
    price: 23.4,
    quantity: 1,
    style: "White T-shirt",
    title: "Cropped Stay Groovy ",
    image: "/images/img1.webp",
    secondimage: "/images/img-1.webp",
  },
  {
    id: 2,
    availableSizes: ["X", "L", "XL", "XXL"],
    currencyFormat: "$",
    currencyId: "USD",
    description: "2.33",
    price: 10.9,
    quantity: 1,
    style: "Wine",
    title: "Basic Cactus White T-shirt",
    image: "/images/img2.webp",
    secondimage: "/images/img-2.webp",
  },
  {
    id: 3,
    availableSizes: ["X", "L", "XL", "XXL"],
    currencyFormat: "$",
    currencyId: "USD",
    description: "3.22",
    price: 10.9,
    quantity: 1,
    style: "Tony Hawk",
    title: "Skater Black Sweatshirt",
    image: "/images/img3.webp",
    secondimage: "/images/img-3.webp",
  },
  {
    id: 4,
    availableSizes: ["X", "L", "XL", "XXL"],
    currencyFormat: "$",
    currencyId: "USD",
    description: "4.21",
    price: 10.9,
    quantity: 1,
    style: "Tule",
    title: "Black Tule Oversized",
    image: "/images/img4.webp",
    secondimage: "/images/img-4.webp",
  },
  {
    id: 5,
    availableSizes: ["X", "L", "XL", "XXL"],
    currencyFormat: "$",
    currencyId: "USD",
    description: "1.23",
    price: 10.9,
    quantity: 1,
    style: "Really Cool T-shirt",
    title: "Black Batman T-shirt",
    image: "/images/img5.webp",
    secondimage: "/images/img-5.webp",
  },
  {
    id: 6,
    availableSizes: ["X", "L", "XL", "XXL"],
    currencyFormat: "$",
    currencyId: "USD",
    description: "4.45",
    price: 10.9,
    quantity: 1,
    style: "Mark Zuck have 365 of this one",
    title: "Blue T-Shirt",
    image: "/images/img6.webp",
    secondimage: "/images/img-6.webp",
  },
  {
    id: 7,
    availableSizes: ["X", "L", "XL", "XXL"],
    currencyFormat: "$",
    currencyId: "USD",
    description: "5.43",
    price: 10.9,
    quantity: 1,
    style: "",
    title: "Loose Black T-shirt",
    image: "/images/img7.webp",
    secondimage: "/images/img-7.webp",
  },
  {
    id: 8,
    availableSizes: ["X", "L", "XL", "XXL"],
    currencyFormat: "$",
    currencyId: "USD",
    description: "2.67",
    price: 10.9,
    quantity: 1,
    style: "White T-shirt",
    title: "Ringer Hall Pass",
    image: "/images/img8.webp",
    secondimage: "/images/img-8.webp",
  },
  {
    id: 9,
    availableSizes: ["X", "L", "XL", "XXL"],
    currencyFormat: "$",
    currencyId: "USD",
    description: "4.67",
    price: 10.9,
    quantity: 1,
    style: "You will like this one",
    title: "Grey T-shirt",
    image: "/images/img9.webp",
    secondimage: "/images/img-9.webp",
  },
  {
    id: 10,
    availableSizes: ["X", "L", "XL", "XXL"],
    currencyFormat: "$",
    currencyId: "USD",
    description: "4.78",
    price: 10.9,
    quantity: 1,
    style: "Adidas originals",
    title: "Black T-shirt with white ",
    image: "/images/img10.webp",
    secondimage: "/images/img-10.webp",
  },
  {
    id: 11,
    availableSizes: ["X", "L", "XL", "XXL"],
    currencyFormat: "$",
    currencyId: "USD",
    description: "6.32",
    price: 10.9,
    quantity: 1,
    style: "Cowabunga!",
    title: "Turtles Ninja T-shirt",
    image: "/images/img11.webp",
    secondimage: "/images/img-11.webp",
  },
  {
    id: 12,
    availableSizes: ["X", "L", "XL", "XXL"],
    currencyFormat: "$",
    currencyId: "USD",
    description: "6.78",
    price: 10.9,
    quantity: 1,
    style: "When you wish well",
    title: "Slim black T-shirt",
    image: "/images/img12.webp",
    secondimage: "/images/img-12.webp",
  },
  {
    id: 13,
    availableSizes: ["X", "L", "XL", "XXL"],
    currencyFormat: "$",
    currencyId: "USD",
    description: "4.67",
    price: 10.9,
    quantity: 1,
    style: "Very comfy",
    title: "Blue Sweatshirt",
    image: "/images/img13.webp",
    secondimage: "/images/img-13.webp",
  },
  {
    id: 14,
    availableSizes: ["X", "L", "XL", "XXL"],
    currencyFormat: "$",
    currencyId: "USD",
    description: "3.67",
    price: 10.9,
    quantity: 1,
    style: "Girl the future is all your",
    title: "White T-shirt Gucci",
    image: "/images/img14.webp",
    secondimage: "/images/img-14.webp",
  },
  {
    id: 15,
    availableSizes: ["X", "L", "XL", "XXL"],
    currencyFormat: "$",
    currencyId: "USD",
    description: "5.67",
    price: 10.9,
    quantity: 1,
    style: "",
    title: "Tropical Wine T-shirt",
    image: "/images/img15.webp",
    secondimage: "/images/img-15.webp",
  },
  {
    id: 16,
    availableSizes: ["X", "L", "XL", "XXL"],
    currencyFormat: "$",
    currencyId: "USD",
    description: "1.43",
    price: 10.9,
    quantity: 1,
    style: "",
    title: "Marine Blue T-shirt",
    image: "/images/img16.webp",
    secondimage: "/images/img-16.webp",
  },
];

export default Data;
